### ISSUE TITLE
Authorized hostnames where Squeak! can be installed

### ISSUE THREAD

**Issue by corywatilo** [PostHog/squeak#107]
… so others can’t take your script, put it on their site, and do bad things with it.

**Comment by corywatilo** [comment]
@joesaunderson Do you know if this got completed?

**Comment by joesaunderson** [comment]
> @joesaunderson Do you know if this got completed?

PR is ready to go, we decided not to merge in before launch, which is less relevant now. So will sort out over weekend...

**Comment by joesaunderson** [comment]
Merged this @corywatilo - it doesn't prevent the snippet from being loaded, but it prevents any questions being shown, added or being replied to.

I think a sensible follow up would be, if the `/questions` API call returns 403 in the snippet, hide any UI automatically, what do you think @smallbrownbike?

**Comment by corywatilo** [comment]
@smallbrownbike I'm going to close this, but if there are any follow-up tasks, please create a new issue
