### ISSUE TITLE
Admin: Issue saving post metadata

### ISSUE THREAD

**Issue by corywatilo** [PostHog/squeak#120]
When clicking the save button, it spins but doesn't update to show a successful saved state, though the changes _do_ seem to have been saved. (This is likely related to me moving these options out of the modal.)

<img width="488" alt="image" src="https://user-images.githubusercontent.com/154479/163723624-f6543d30-af52-4bfd-b968-66466494b9f0.png">

**Comment by joesaunderson** [comment]
I'll fix this now, think it's related to the modal being removed.

**Comment by joesaunderson** [comment]
Fixed in https://github.com/PostHog/squeak/pull/121
