### ISSUE TITLE
Support multiple slugs, separated by commas

### ISSUE THREAD

**Issue by corywatilo** [PostHog/squeak#123]
As is, this doesn't seem to let me show the same question on multiple URLs

<img width="331" alt="image" src="https://user-images.githubusercontent.com/154479/163733281-e4ed4c64-d689-4c15-b37d-3521b26ff7e4.png">

**Comment by joesaunderson** [comment]
This is stored in the DB as an array, I suggest we make the UI better.

Could we should this as a table, like the allowed origins piece (also stored as an array of strings) - with the option to add/remove

**Comment by corywatilo** [comment]
Nope, no reason. Whatever is easier for the back end works for me!
