### ISSUE TITLE
Admin console

### ISSUE THREAD

**Issue by joesaunderson** [PostHog/squeak#15]
We should provide a method of managing (deletion etc) questions/answers from the admin UI

We should also allow for editing of questions/responses to fix typos and to remove out-of-date information that may be confusing.

- [x] View/delete questions/responses @smallbrownbike 
- [x] Users table (with role?) @joesaunderson 
- [x] Edit user: email, name, role @joesaunderson 
- [x] Settings pages (modify API keys for services, copy/paste JS code) @joesaunderson 
- [x] Invite user link to invite your team, then make it clear you need to upgrade their role @joesaunderson

**Comment by corywatilo** [comment]
If we don’t get to this before launch, we should just add a notice to the admin explaining how to moderate content in Supabase for the time being.

**Comment by corywatilo** [comment]
- Show questions, sorted by recently updated?
- Support question/response deletion (with js confirm)
- Show author, subject, timestamp, slugs
- Click a question to see thread
- Maybe design using `/questions` UI (with admin controls)

**Comment by joesaunderson** [comment]
> Edit user: email, name, role @joesaunderson

For MVP, have allowed role editing, email and name requires some more work / thinking - created https://github.com/PostHog/squeak/issues/25 as a follow up.
