### ISSUE TITLE
Sanitize question permalink slugs

### ISSUE THREAD

**Issue by corywatilo** [PostHog/squeak#267]
Since question slugs are generated from the titles, we need to handle special characters and other things that shouldn't be in URLs. For example:

https://posthog.com/questions/typeerror:-cannot-read-property-'identify'-of-undefined-getting-this-when-i-use-posthog.identify

In above:

- [ ] `:`
- [ ] `'`
- [ ] `.`

**Comment by smallbrownbike** [comment]
Closed via #270
