### ISSUE TITLE
Use enum for role

### ISSUE THREAD

**Issue by joesaunderson** [PostHog/squeak#6]
In `squeak_profiles_readonly`, we should create an enum to represent the roles (currently `user` and `admin` - but there may be a concept of `moderator` in future?)

**Comment by corywatilo** [comment]
In the UI today, is there any difference between Moderator and Admin, or they’re just different on the front end but don’t have any distinctive functionality yet?

**Comment by joesaunderson** [comment]
> In the UI today, is there any difference between Moderator and Admin, or they’re just different on the front end but don’t have any unique permissions yet?

At the moment there's no difference other than admins can 'do' more (login to the admin etc) - moderators are 'staff' users that would reply using the snippet, but not have a login.
